### ISSUE TITLE
Rj45 vs Rj11/12

### ISSUE THREAD

**Issue by LuddesGarag** [u9n/hanporten#12]
På marknaden verkar just nu de flesta tillverkare av smart hemutrustning använda rj45 för att ansluta till elmätaren. Men samtidigt har många mätare rj11 eller rj12. Skulle ni säga att det är möjligt att göra en adapter mellan dessa två fysiska gränssnitt?

**Comment by Krolken** [comment]
Det är för att Norge var först ut med att standardisera här i Norden och det sattes även upp mätare med RJ45 innan den svenska standarden var klar. 
Vad jag vet jobbar lite företag med att ta fram produkter för den svenska standarden.

Det är definitivt möjligt att göra en adapter. Jag skissade lite på det och det är enkelt att lösa i mjukvara. Det som tar tid och kostar pengar att utveckla är hårdvaran. 
Problemet är inte bara att det är två olika fysiska gränssnitt utan också att protokollen är olika.

Men det går att använda våra python bibliotek för DLMS/COSEM https://github.com/pwitab/dlms-cosem och IEC62056-21 https://github.com/pwitab/iec62056-21 till att skriva omvandlingen. Vill man dock ha en mer kompakt lösning vill man inte köra Python utan något embedded. Men det är inte jättemycket jobb att parsa output:en eftersom den är rätt statisk i formatet.

**Comment by LuddesGarag** [comment]
Okej då förstår jag. Trodde det var samma protokoll och bara en skillnad kontaktdonen. Det var en sådan adapter jag hade i åtanke men då vet jag att det inte SÅ enkelt. :-)
Har du någon koll på vilka som siktar på att komma med produkter för Svenska smarta elmätare? Tänkte så kan kan vara på hugget när det finns något att köpa.

**Comment by Krolken** [comment]
Tibber borde ju komma med något snart tycker jag. Det är ju en rätt stor del av deras erbjudande att kunna koppla upp det.

Sen beror det ju på vad du vill ha. Ska du kunna koppla upp den mot Home assistant eller ska det passa med någon annan produkt. Jag tror att tibbers kommer bara gå till Tibbers servrar och du kan inte använda den med något annat i huset.

Den svenska standarden baseras ju på den nederländska DSMR så de flesta saker som fungerar med P1 DSMR "borde" fungera med den svenska.  Tex: https://www.zuidwijk.com/product/p1-reader-ethernet-v3-3/ eller https://opencircuit.shop/Product/Smart-meter-reader-V4.5-Assembled-programmed

**Comment by Krolken** [comment]
Closing since question is answered.
