### ISSUE TITLE
Data to be used when calculating CRC

### ISSUE THREAD

**Issue by larsgarden1** [u9n/hanporten#13]
Hi,

I have the swedish net owner Ellevio, and a Segemcom S211 meter.
When calculating the message checksum, the characters '/' and '!' needs to be added in the calculation. 

Under "Svenska porten (RJ12)" -> Protokollet, paragraph "Meddelandestruktur" it says:

"Datan som skall användas i beräkningen är de byte som är mellan / och !."

This is wrong. '/' and '!' must be added in the CRC calculation.

Best regards /M

**Comment by Krolken** [comment]
You are correct! Good catch.
