### ISSUE TITLE
Nacka Energi och Kaifa CL 109

### ISSUE THREAD

**Issue by Arneby** [u9n/hanporten#15]
Nacka Energi installerar just nu en Kaifa CL 109 (MA304H4E) i hela kommunen. Den har en RJ12 HAN-port och ser ut som enligt bild:
![2021-09-22 23 58 39](https://user-images.githubusercontent.com/63608198/134428011-918fc333-db13-422f-8155-dee48bb1672b.jpg)

**Comment by Krolken** [comment]
Nice. Bra att de har börjat leverera enligt den svenska standarden. Jag har bara sett Kaifa med den norska än så länge.

**Comment by Krolken** [comment]
Vet du hur man akriverar porten hos Nacka Energi? Kan man göra det själv eller måste man kontakta kundtjänst?
