### ISSUE TITLE
Exempel på hur man läser data från Skellefteå Krafts Aidon mätare med RJ45

### ISSUE THREAD

**Issue by OlleRatu** [u9n/hanporten#23]
[HAN_aidon_rj45.zip](https://github.com/u9n/hanporten/files/8548832/HAN_aidon_rj45.zip)

Hej,
Jag har gjort ett exempelprogram som läser Skellefteå Krafts Aidon mätare med RJ45.
Den svenska varianten på protokollet.

Python3, en gammal Raspberry Pi och ett M-Bus client kort från Mikroe.

Hoppas nån kan använda sig av koden.

**Comment by Krolken** [comment]
Har du en repo där man kan se koden? Att ladda ner random zip i en issue känns inte säkert. Jag länkar gärna på sidan.

**Comment by OlleRatu** [comment]
Nä, det har du rätt i.
Ska fixa en på github.

**Comment by OlleRatu** [comment]
Länk till repo.
https://github.com/OlleRatu/han-rj45
