### ISSUE TITLE
Sluta kalla P1 för HAN !

### ISSUE THREAD

**Issue by RicardP** [u9n/hanporten#25]
Antingen är det P1 eller HAN, men i Sverige är det P1 som gäller och inte norska HAN med Mbus.

**Comment by Krolken** [comment]
Tja. Ska man vara nitisk så är det H1-porten den kallas i de svenska branchrekommendationerna enligt IEC-standard. Men det ligger inte lika bra i munnen. 

De flesta nätbolag benämner den också som HAN-port. 

Skall man prata om båda är det bättre att prata om konceptet kring ett lokalt kundgränssnitt, ett HAN-interface. 

Har du något mer konstruktivt får du gärna öppna ärendet igen.
