### ISSUE TITLE
Anslutning till hanport via com-port hw-schema

### ISSUE THREAD

**Issue by bergmanhenrik** [u9n/hanporten#26]
![Han-comport](https://user-images.githubusercontent.com/109045557/178164108-669c03b6-33e0-4f79-82cf-d94ec043bece.png)
hanporten.se är utmärkt för att samla uppgifter kring de nya elmätarna och dess RJ12-anslutning.
tänkte bidraga med lite hw-schema för koppling till en vanlig DB-9-kontakt.
Varför sidans inverterade signal finns med förstår jag ej. Dessutom är det schemat inte att rekommendera. Om någon vill ha eller behöver inverterade signaler har jag ett bättre förslag.
Synpunkter på detta mottages.
/Henrik Bergman

**Comment by Krolken** [comment]
Tack tack :)

Kopplar du detta till en RS232 krets eller är det fortfarande 5V TTL och bara en DB9 som kontakt.

RS232 finns i lite olika i spänningsnivåer och kanske inte passar alla kretsar. Osäker också om alla kretsar registrerar 0V som ok signal.

Anledningen till att du inte behöver invertera med RS232 är väl att de ser -3 - -15 V som etta och +3 - +15 V som nolla. Det är ju redan en invetering från open collector.
Open collector drar ner signalen till GND vid etta och med pull up resistor till VCC vid nolla. Så för att läsa av den på TTL nivå måste man invertera. Har man ett FTDI-chip kan man invertera direkt i det med inställningar, men kanske enklare att fixa med en transistor.

Hur skulle du vilja ändra kretsen?

**Comment by Krolken** [comment]
Stänger pga inaktivitet.
