### ISSUE TITLE
DSMR referens

### ISSUE THREAD

**Issue by AndersHoglund** [u9n/hanporten#28]
Borde man inte nämna någon stans att den modifierade standarden iec62056-21 som används även kallas DSMR och är specade här: 
(https://www.netbeheernederland.nl/_upload/Files/Slimme_meter_15_a727fce1f1.pdf)

Om det nu är så det är, att DSMR och den svenska modifieringen av standarden faktiskt är de samma..... Verkar vara så, men svårt att hitta exakta uppgifter om detta.

**Comment by Krolken** [comment]
Den svenska standarden baseras på DSMR P1 Companion Standard som du länkar, men allt är inte med i den. 
Det är viktigt att specificera P1 Companion Standard för det är den som pratar om P1-porten. För övrigt är DSMR sin egen companion standard för DLMS/COSEM för den nederländska marknaden. Det vill säga exakt hur alla elmätare i Nederländerna skall implementera DLMS/COSEM för att garantera interoperabilitet. 

Det vore nog bra att länka det dokumenten någonstans. Kanske under "Svenska branchrekomendationen".

I branchrekommendationen står det:

> Energiföretagen Sverige föreslår att det lokala kundgränssnittet på elmätare utformas
som ett fysiskt gränssnitt, utförande baserat på den nederländska implementeringen
beskriven i ”P1 Companion Standard, version 5.0.2” och alltså baserat på IEC 62056-21
Mode D, samt med de ändringar och kompletteringar som framgår av detta dokument.

**Comment by AndersHoglund** [comment]
Tack. Vilken soppa! 
Vore nog bra om Holländska standarden nämndes pss som den Norska nämns, och naturligtvis skillnaderna mot den Svenska. Samt länkar till dokumenten som definierar samtliga dessa. Finns det fler lokala "standards"?

Det förekommer rekommendationer på nätet att använda "HomeWizard P1-meter" i Sverige trots att den enbart är avsedd för Holland och Belgien enligt manualen. Påstås att den skulle funka i Sverige, vilket då inte skulle vara 100% sanning. Vilka problem kan man förväntas få om man använder denna i Sverige? Vissa data som inte kan visas?
Ref: (https://www.homewizard.com/p1-meter/ )
/A

**Comment by Krolken** [comment]
Det bör oftast fungera.  Men det beror ju litet på vad elnätbolget har beställt i sina mätare. De är ju bara en rekommendation och inte krav så det är möjligt att det finns avsteg från P1 Companion Standard.
