### ISSUE TITLE
Certificate error https

### ISSUE THREAD

**Issue by Anteus** [u9n/hanporten#3]
Seems to be trouble with the https certificate. Says on iOS safari issued by GitHub. Try toggling https to make it reissue a new cert from let's encrypt.

**Comment by Krolken** [comment]
Did you try the link on byggahus? I wrote the address with www but it is set up to be without. 

I have edited the link on byggahus now to be the correct one.

**Comment by Anteus** [comment]
That issue again. To make GitHub generate a cert for both change address to with www and wait until you can turn on https and activate that and serving www with correct cert. Then you can change the address back.

**Comment by Krolken** [comment]
I never really did anything about this but seems to work now :)
