### ISSUE TITLE
Document Tekniska verken RJ12

### ISSUE THREAD

**Issue by Krolken** [u9n/hanporten#4]
Tekniska Verken uses an Aidon meter that has an RJ12 connector but pushes a HDLC frame containing a DataNotification APDU.

Document the deviance from standard and add code example to parse the data.

**Comment by xpagedeveloper** [comment]
Found documentation
https://www.tekniskaverken.se/siteassets/tekniska-verken/elnat/aidonfd-rj12-han-interface-se-v13a.cleaned.pdf

**Comment by Krolken** [comment]
Goodie. So there is then 3 setups as I have understood it at Tekniska verken.

RJ12 + Svensk branchstandard
RJ12 + Norsk standard
RJ45 + Norsk standard
